apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  namespace: mini-eshop
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: eshop-lab-pass
  ConnectionStrings__Catalog: "Host=postgres;Port=5432;Database=catalog_db;Username=postgres;Password=eshop-lab-pass"
  ConnectionStrings__Orders: "Host=postgres;Port=5432;Database=orders_db;Username=postgres;Password=eshop-lab-pass"
  ConnectionStrings__Notifications: "Host=postgres;Port=5432;Database=notifications_db;Username=postgres;Password=eshop-lab-pass"
  ConnectionStrings__Reviews: "Host=postgres;Port=5432;Database=reviews_db;Username=postgres;Password=eshop-lab-pass"
